In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv

In [2]:
# Load database credentials
load_dotenv("../.env")

db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

# Connect to MySQL
engine = create_engine(
    f"mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
)

In [3]:
# Load property sales data from MySQL
query = """
SELECT *
FROM property_sales;
"""

df = pd.read_sql(query, engine)

df.head()

,borough,neighborhood,building_class_category,tax_class_at_present,block,lot,building_class_at_present,address,zip_code,residential_units,commercial_units,total_units,land_square_feet,gross_square_feet,year_built,tax_class_at_time_of_sale,building_class_at_time_of,sale_price,sale_date,apartment_number
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,372,9,C7,272 EAST 3 STREET,10009,8,1,9,"2,021",7129,1900,2,C7,0,2025-12-15T00:00:00.000,NaN
1,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,376,41,C6,"745 EAST 6TH STREET, 1B",10009,28,0,28,"4,542",18254,1900,2,C4,540000,2025-12-17T00:00:00.000,NaN
2,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,377,50,C2,"275 EAST 7TH STREET, 3",10009,5,0,5,"2,169",6294,1900,2,C2,1250000,2026-05-27T00:00:00.000,NaN
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,385,38,C6,"21-23 AVENUE C, 5B",10009,20,2,22,"3,315",17160,1900,2,C4,0,2025-11-11T00:00:00.000,NaN
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,385,50,C4,240 EAST 2ND STREET,10009,24,0,24,"2,623",11322,1910,2,C4,0,2026-05-29T00:00:00.000,NaN

In [5]:
df.shape

(82345, 20)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 82345 entries, 0 to 82344
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   borough                    82345 non-null  str
 1   neighborhood               82345 non-null  str
 2   building_class_category    82345 non-null  str
 3   tax_class_at_present       82345 non-null  str
 4   block                      82345 non-null  str
 5   lot                        82345 non-null  str
 6   building_class_at_present  82345 non-null  str
 7   address                    82345 non-null  str
 8   zip_code                   82329 non-null  str
 9   residential_units          62095 non-null  str
 10  commercial_units           47531 non-null  str
 11  total_units                65210 non-null  str
 12  land_square_feet           44416 non-null  str
 13  gross_square_feet          44416 non-null  str
 14  year_built                 76949 non-null  str
 15  tax_class_at_time_of_sale  82345 non-null  str
 16  building_class_at_time_of  82345 non-null  str
 17  sale_price                 82345 non-null  str
 18  sale_date                  82345 non-null  str
 19  apartment_number           20717 non-null  str
dtypes: str(20)
memory usage: 12.6 MB

In [7]:
# Check missing values
df.isna().sum()

borough                          0
neighborhood                     0
building_class_category          0
tax_class_at_present             0
block                            0
lot                              0
building_class_at_present        0
address                          0
zip_code                        16
residential_units            20250
commercial_units             34814
total_units                  17135
land_square_feet             37929
gross_square_feet            37929
year_built                    5396
tax_class_at_time_of_sale        0
building_class_at_time_of        0
sale_price                       0
sale_date                        0
apartment_number             61628
dtype: int64

In [8]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [9]:
# Check current data types
df.dtypes

borough                      str
neighborhood                 str
building_class_category      str
tax_class_at_present         str
block                        str
lot                          str
building_class_at_present    str
address                      str
zip_code                     str
residential_units            str
commercial_units             str
total_units                  str
land_square_feet             str
gross_square_feet            str
year_built                   str
tax_class_at_time_of_sale    str
building_class_at_time_of    str
sale_price                   str
sale_date                    str
apartment_number             str
dtype: object

In [10]:
# Check empty strings
(df == "").sum()

borough                      0
neighborhood                 0
building_class_category      0
tax_class_at_present         0
block                        0
lot                          0
building_class_at_present    0
address                      0
zip_code                     0
residential_units            0
commercial_units             0
total_units                  0
land_square_feet             0
gross_square_feet            0
year_built                   0
tax_class_at_time_of_sale    0
building_class_at_time_of    0
sale_price                   0
sale_date                    0
apartment_number             0
dtype: int64

In [11]:
# Check important numeric columns
numeric_columns = [
    "sale_price",
    "residential_units",
    "commercial_units",
    "total_units",
    "land_square_feet",
    "gross_square_feet",
    "year_built"
]

df[numeric_columns].head(10)

,sale_price,residential_units,commercial_units,total_units,land_square_feet,gross_square_feet,year_built
0,0,8,1,9,"2,021",7129,1900
1,540000,28,0,28,"4,542",18254,1900
2,1250000,5,0,5,"2,169",6294,1900
3,0,20,2,22,"3,315",17160,1900
4,0,24,0,24,"2,623",11322,1910
5,8600000,28,2,30,"4,544",19418,1900
6,4665000,5,0,5,"1,080",3328,1910
7,0,30,0,30,"4,508",18732,1900
8,6850000,8,1,9,"1,909",6245,1951
9,129316,12,0,12,"2,370",10715,1900

In [12]:
# Convert numeric columns
numeric_columns = [
    "borough",
    "block",
    "lot",
    "zip_code",
    "residential_units",
    "commercial_units",
    "total_units",
    "land_square_feet",
    "gross_square_feet",
    "year_built",
    "sale_price"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

In [13]:
# Convert sale date to datetime
df["sale_date"] = pd.to_datetime(
    df["sale_date"],
    errors="coerce"
)

In [14]:
# Check our updated data types
df.dtypes

borough                               int64
neighborhood                            str
building_class_category                 str
tax_class_at_present                    str
block                                 int64
lot                                   int64
building_class_at_present               str
address                                 str
zip_code                            float64
residential_units                   float64
commercial_units                    float64
total_units                         float64
land_square_feet                    float64
gross_square_feet                   float64
year_built                          float64
tax_class_at_time_of_sale               str
building_class_at_time_of               str
sale_price                            int64
sale_date                    datetime64[us]
apartment_number                        str
dtype: object

In [15]:
# Check sale price distribution
df["sale_price"].describe()

count    8.234500e+04
mean     2.106522e+06
std      1.340801e+07
min      0.000000e+00
25%      0.000000e+00
50%      5.250000e+05
75%      1.150000e+06
max      5.722903e+08
Name: sale_price, dtype: float64

In [16]:
# Check zero-dollar sales
(df["sale_price"] == 0).sum()

np.int64(28332)

In [17]:
# Check low sale prices
df[df["sale_price"] < 1000]["sale_price"].value_counts().sort_index()

sale_price
0      28332
1        241
2          4
3          9
4         17
5          1
7          6
10       978
20         5
21        21
25         3
38         1
100       63
250        1
300        2
390        1
500       61
610        2
650        1
900        1
Name: count, dtype: int64

In [18]:
# Look at low-price transactions
df.loc[
    df["sale_price"] < 1000,
    [
        "borough",
        "neighborhood",
        "building_class_category",
        "address",
        "sale_price",
        "sale_date"
    ]
].head(20)

,borough,neighborhood,building_class_category,address,sale_price,sale_date
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,272 EAST 3 STREET,0,2025-12-15
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,"21-23 AVENUE C, 5B",0,2025-11-11
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,240 EAST 2ND STREET,0,2026-05-29
7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,299 EAST 8TH STREET,0,2026-05-19
13,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,520 EAST 11TH STREET,0,2025-09-19
15,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,512 EAST 13TH STREET,0,2026-05-29
16,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,"544 EAST 13TH STREET, 4C",0,2025-10-02
18,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,515 EAST 12 STREET,0,2026-04-20
36,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,"368 EAST 8TH STREET, 6A",0,2026-02-19
43,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,"206 EAST 7TH STREET, 5",0,2026-04-13
49,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,"209 EAST 7TH STREET, 4N",0,2025-10-27
50,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,"209 EAST 7TH STREET, 4W",0,2025-10-31
87,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,"515 EAST 13TH STREET, 8",0,2025-09-03
89,1,ALPHABET CITY,10 COOPS - ELEVATOR APARTMENTS,"226 EAST 2ND STREET, 1C",0,2026-02-04
96,1,ALPHABET CITY,12 CONDOS - WALKUP APARTMENTS,"613 EAST 11TH STREET, A1",10,2026-04-15
99,1,ALPHABET CITY,12 CONDOS - WALKUP APARTMENTS,"503 EAST 13 STREET, C1",0,2025-10-08
100,1,ALPHABET CITY,12 CONDOS - WALKUP APARTMENTS,"503 EAST 13TH STREET, G2",0,2025-12-01
102,1,ALPHABET CITY,13 CONDOS - ELEVATOR APARTMENTS,"229 EAST 2 STREET, 1B/2A",0,2026-05-01
103,1,ALPHABET CITY,13 CONDOS - ELEVATOR APARTMENTS,"217 EAST 7TH STREET, 2B",0,2026-05-01
104,1,ALPHABET CITY,13 CONDOS - ELEVATOR APARTMENTS,"143 AVENUE B, 4E",0,2026-07-14

In [19]:
# Keep transactions with meaningful sale prices
df_clean = df[df["sale_price"] >= 1000].copy()

In [20]:
# Check how many rows remain
print("Original rows:", len(df))
print("Clean rows:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 82345
Clean rows: 52595
Rows removed: 29750

In [21]:
# Replace borough codes with borough names
borough_map = {
    1: "Manhattan",
    2: "Bronx",
    3: "Brooklyn",
    4: "Queens",
    5: "Staten Island"
}

df_clean["borough"] = df_clean["borough"].map(borough_map)

In [22]:
# Check borough names
df_clean["borough"].value_counts()

borough
Queens           15736
Manhattan        15069
Brooklyn         13661
Staten Island     4170
Bronx             3959
Name: count, dtype: int64

In [23]:
# Check the oldest building years
df_clean["year_built"].value_counts().sort_index().head(20)

year_built
35.0       1
1800.0    21
1824.0     2
1826.0     1
1827.0     1
1829.0     6
1833.0     1
1834.0     1
1836.0     2
1840.0     1
1845.0     1
1846.0     3
1849.0     3
1850.0     8
1853.0     1
1856.0     3
1857.0     1
1858.0     1
1860.0     2
1862.0     1
Name: count, dtype: int64

In [24]:
# Replace invalid year built values with missing values
df_clean.loc[df_clean["year_built"] < 1800, "year_built"] = pd.NA

# Check the minimum year built
df_clean["year_built"].min()

np.float64(1800.0)

In [25]:
# Check zero square footage
(df_clean["gross_square_feet"] == 0).sum()

np.int64(1014)

In [26]:
# Check smallest square footage values
df_clean["gross_square_feet"].value_counts().sort_index().head(20)

gross_square_feet
0.0      1014
105.0       1
172.0       1
231.0       1
289.0       1
291.0       1
300.0       2
306.0       2
320.0       2
360.0       1
380.0       1
385.0       1
392.0       1
400.0       2
416.0       1
417.0       1
420.0       4
425.0       1
438.0       1
440.0       1
Name: count, dtype: int64

In [27]:
# Replace zero square footage with missing values
df_clean.loc[df_clean["gross_square_feet"] == 0, "gross_square_feet"] = pd.NA

# Check that zero square footage values are gone
(df_clean["gross_square_feet"] == 0).sum()

np.int64(0)

In [28]:
# Check for negative unit values
print("Residential:", (df_clean["residential_units"] < 0).sum())
print("Commercial:", (df_clean["commercial_units"] < 0).sum())
print("Total:", (df_clean["total_units"] < 0).sum())

Residential: 0
Commercial: 0
Total: 0

In [29]:
# Check zero land square footage
(df_clean["land_square_feet"] == 0).sum()

np.int64(14)

In [30]:
# Replace zero land square footage with missing values
df_clean.loc[df_clean["land_square_feet"] == 0, "land_square_feet"] = pd.NA

# Check that zero values are gone
(df_clean["land_square_feet"] == 0).sum()

np.int64(0)

In [31]:
# Create price per square foot
df_clean["price_per_sqft"] = (
    df_clean["sale_price"] / df_clean["gross_square_feet"]
)

In [32]:
df_clean["price_per_sqft"].head(10)

1       29.582557
2      198.601843
5      442.888042
6     1401.742788
8     1096.877502
9       12.068689
10      15.278955
11      15.279048
12    1228.021211
14     678.571429
Name: price_per_sqft, dtype: float64

In [33]:
# Create date features
df_clean["sale_year"] = df_clean["sale_date"].dt.year
df_clean["sale_month"] = df_clean["sale_date"].dt.month
df_clean["sale_quarter"] = df_clean["sale_date"].dt.quarter

In [34]:
# Check date features
df_clean[
    ["sale_date", "sale_year", "sale_month", "sale_quarter"]
].head()

   sale_date  sale_year  sale_month  sale_quarter
1 2025-12-17       2025          12             4
2 2026-05-27       2026           5             2
5 2026-03-09       2026           3             1
6 2026-03-25       2026           3             1
8 2026-05-14       2026           5             2

In [35]:
# Create property age
df_clean["property_age"] = (
    df_clean["sale_year"] - df_clean["year_built"]
)

In [36]:
# Check property age
df_clean[
    ["year_built", "sale_year", "property_age"]
].head(10)

    year_built  sale_year  property_age
1       1900.0       2025         125.0
2       1900.0       2026         126.0
5       1900.0       2026         126.0
6       1910.0       2026         116.0
8       1951.0       2026          75.0
9       1900.0       2026         126.0
10      1900.0       2026         126.0
11      1900.0       2026         126.0
12      1900.0       2025         125.0
14      1900.0       2026         126.0

In [37]:
# Check final dataset shape
print("Original shape:", df.shape)
print("Clean shape:", df_clean.shape)

Original shape: (82345, 20)
Clean shape: (52595, 25)

In [ ]:
# Check final missing values
# Some nulls are expected because certain fields do not apply to every property.
# Square footage and unit information are not reported for many transactions.
# These rows are kept because they can still be used for sale price, location, and other analyses.
df_clean.isna().sum()

borough                          0
neighborhood                     0
building_class_category          0
tax_class_at_present             0
block                            0
lot                              0
building_class_at_present        0
address                          0
zip_code                        13
residential_units            16249
commercial_units             26800
total_units                  13911
land_square_feet             52266
gross_square_feet            30152
year_built                    3394
tax_class_at_time_of_sale        0
building_class_at_time_of        0
sale_price                       0
sale_date                        0
apartment_number             37397
price_per_sqft               30152
sale_year                        0
sale_month                       0
sale_quarter                     0
property_age                  3394
dtype: int64

In [39]:
# Check final data types
df_clean.dtypes

borough                                 str
neighborhood                            str
building_class_category                 str
tax_class_at_present                    str
block                                 int64
lot                                   int64
building_class_at_present               str
address                                 str
zip_code                            float64
residential_units                   float64
commercial_units                    float64
total_units                         float64
land_square_feet                    float64
gross_square_feet                   float64
year_built                          float64
tax_class_at_time_of_sale               str
building_class_at_time_of               str
sale_price                            int64
sale_date                    datetime64[us]
apartment_number                        str
price_per_sqft                      float64
sale_year                             int32
sale_month                            int32
sale_quarter                          int32
property_age                        float64
dtype: object

In [40]:
# Save cleaned dataset
df_clean.to_csv(
    "../data/processed/property_sales_clean.csv",
    index=False
)